package routes

import (
	"github.com/gin-gonic/gin"
	controller "wms-api/controller/billing"
	"wms-api/middleware"
)

func registerBillingRoutes(api *gin.RouterGroup, controller *controller.Controller, authorization *middleware.Authentication) {
	group := api.Group("/billing")
	group.Use(authorization.RequireSession())
	group.Use(controller.RequireScope())
	read := authorization.RequirePermission(middleware.PermissionBillingRead)
	configure := authorization.RequirePermission(middleware.PermissionBillingConfigure)
	prepare := authorization.RequirePermission(middleware.PermissionBillingPrepare)
	approve := authorization.RequirePermission(middleware.PermissionBillingApprove)
	issue := authorization.RequirePermission(middleware.PermissionBillingIssue)
	payment := authorization.RequirePermission(middleware.PermissionBillingPayment)

	group.POST("/contracts", configure, controller.CreateContract)
	group.GET("/contracts", read, controller.ListContracts)
	group.GET("/contracts/:id", read, controller.GetContract)
	group.PUT("/contracts/:id", configure, controller.UpdateContract)
	group.POST("/contracts/:id/activate", approve, controller.ActivateContract)
	group.POST("/contracts/:id/suspend", approve, controller.SuspendContract)
	group.POST("/contracts/:id/expire", approve, controller.ExpireContract)
	group.POST("/contracts/:id/resume", approve, controller.ResumeContract)
	group.POST("/contracts/:id/terminate", approve, controller.TerminateContract)
	group.POST("/contracts/:id/events/manual", prepare, controller.CreateManualEvent)
	group.POST("/rate-cards", configure, controller.CreateRateCard)
	group.GET("/rate-cards", read, controller.ListRateCards)
	group.GET("/rate-cards/:id", read, controller.GetRateCard)
	group.PUT("/rate-cards/:id", configure, controller.UpdateRateCard)
	group.POST("/rate-cards/:id/lines", configure, controller.AddRateCardLine)
	group.PUT("/rate-cards/:id/lines/:line_id", configure, controller.UpdateRateCardLine)
	group.DELETE("/rate-cards/:id/lines/:line_id", configure, controller.DeleteRateCardLine)
	group.POST("/rate-cards/:id/approve", approve, controller.ApproveRateCard)
	group.POST("/rate-cards/:id/activate", approve, controller.ActivateRateCard)
	group.POST("/rate-cards/:id/expire", approve, controller.ExpireRateCard)
	group.POST("/rate-cards/:id/cancel", approve, controller.CancelRateCard)
	group.POST("/events/collect", prepare, controller.CollectEvents)
	group.POST("/events/storage-snapshot", prepare, controller.SnapshotStorage)
	group.GET("/events", read, controller.ListEvents)
	group.GET("/events/:id", read, controller.GetEvent)
	group.POST("/events/:id/exclude", approve, controller.ExcludeEvent)
	group.POST("/runs", prepare, controller.CreateRun)
	group.GET("/runs", read, controller.ListRuns)
	group.GET("/runs/:id", read, controller.GetRun)
	group.POST("/runs/:id/calculate", prepare, controller.CalculateRun)
	group.POST("/runs/:id/review", approve, controller.ReviewRun)
	group.POST("/runs/:id/reopen", approve, controller.ReopenRun)
	group.POST("/runs/:id/cancel", approve, controller.CancelRun)
	group.POST("/runs/:id/invoice", prepare, controller.CreateInvoice)
	group.GET("/invoices", read, controller.ListInvoices)
	group.GET("/invoices/:id", read, controller.GetInvoice)
	group.PUT("/invoices/:id", prepare, controller.UpdateInvoice)
	group.POST("/invoices/:id/review", approve, controller.ReviewInvoice)
	group.POST("/invoices/:id/reopen", approve, controller.ReopenInvoice)
	group.POST("/invoices/:id/issue", issue, controller.IssueInvoice)
	group.POST("/invoices/:id/void", issue, controller.VoidInvoice)
	group.POST("/invoices/:id/credit-notes", issue, controller.IssueCreditNote)
	group.GET("/invoices/:id/credit-notes", read, controller.ListCreditNotes)
	group.POST("/invoices/:id/payments", payment, controller.RecordPayment)
	group.GET("/invoices/:id/payments", read, controller.ListPayments)
}
