package routes

import (
	"github.com/gin-gonic/gin"
	controller "wms-api/controller/billing"
)

func registerBillingRoutes(api *gin.RouterGroup, controller *controller.Controller, requireSession gin.HandlerFunc) {
	group := api.Group("/billing")
	group.Use(requireSession)
	group.Use(controller.RequireScope())
	group.POST("/contracts", controller.CreateContract)
	group.GET("/contracts", controller.ListContracts)
	group.GET("/contracts/:id", controller.GetContract)
	group.PUT("/contracts/:id", controller.UpdateContract)
	group.POST("/contracts/:id/activate", controller.ActivateContract)
	group.POST("/contracts/:id/suspend", controller.SuspendContract)
	group.POST("/contracts/:id/expire", controller.ExpireContract)
	group.POST("/contracts/:id/resume", controller.ResumeContract)
	group.POST("/contracts/:id/terminate", controller.TerminateContract)
	group.POST("/contracts/:id/events/manual", controller.CreateManualEvent)
	group.POST("/rate-cards", controller.CreateRateCard)
	group.GET("/rate-cards", controller.ListRateCards)
	group.GET("/rate-cards/:id", controller.GetRateCard)
	group.PUT("/rate-cards/:id", controller.UpdateRateCard)
	group.POST("/rate-cards/:id/lines", controller.AddRateCardLine)
	group.PUT("/rate-cards/:id/lines/:line_id", controller.UpdateRateCardLine)
	group.DELETE("/rate-cards/:id/lines/:line_id", controller.DeleteRateCardLine)
	group.POST("/rate-cards/:id/approve", controller.ApproveRateCard)
	group.POST("/rate-cards/:id/activate", controller.ActivateRateCard)
	group.POST("/rate-cards/:id/expire", controller.ExpireRateCard)
	group.POST("/rate-cards/:id/cancel", controller.CancelRateCard)
	group.POST("/events/collect", controller.CollectEvents)
	group.POST("/events/storage-snapshot", controller.SnapshotStorage)
	group.GET("/events", controller.ListEvents)
	group.GET("/events/:id", controller.GetEvent)
	group.POST("/events/:id/exclude", controller.ExcludeEvent)
	group.POST("/runs", controller.CreateRun)
	group.GET("/runs", controller.ListRuns)
	group.GET("/runs/:id", controller.GetRun)
	group.POST("/runs/:id/calculate", controller.CalculateRun)
	group.POST("/runs/:id/review", controller.ReviewRun)
	group.POST("/runs/:id/reopen", controller.ReopenRun)
	group.POST("/runs/:id/cancel", controller.CancelRun)
	group.POST("/runs/:id/invoice", controller.CreateInvoice)
	group.GET("/invoices", controller.ListInvoices)
	group.GET("/invoices/:id", controller.GetInvoice)
	group.PUT("/invoices/:id", controller.UpdateInvoice)
	group.POST("/invoices/:id/review", controller.ReviewInvoice)
	group.POST("/invoices/:id/reopen", controller.ReopenInvoice)
	group.POST("/invoices/:id/issue", controller.IssueInvoice)
	group.POST("/invoices/:id/void", controller.VoidInvoice)
	group.POST("/invoices/:id/credit-notes", controller.IssueCreditNote)
	group.GET("/invoices/:id/credit-notes", controller.ListCreditNotes)
	group.POST("/invoices/:id/payments", controller.RecordPayment)
	group.GET("/invoices/:id/payments", controller.ListPayments)
}
