package routes

import (
	controller "wms-api/controller/inbound"
	"wms-api/middleware"

	"github.com/gin-gonic/gin"
)

func registerInboundRoutes(api *gin.RouterGroup, controller *controller.Controller, authorization *middleware.Authentication) {
	group := api.Group("/inbound")
	group.Use(authorization.RequireSession())
	group.Use(controller.RequireScope())
	read := authorization.RequirePermission(middleware.PermissionInboundRead)
	plan := authorization.RequirePermission(middleware.PermissionInboundPlan)
	approve := authorization.RequirePermission(middleware.PermissionInboundApprove)
	receive := authorization.RequirePermission(middleware.PermissionInboundReceive)
	qc := authorization.RequirePermission(middleware.PermissionInboundQC)
	putaway := authorization.RequirePermission(middleware.PermissionInboundPutaway)
	assign := authorization.RequirePermission(middleware.PermissionInboundAssign)
	dispose := authorization.RequirePermission(middleware.PermissionInboundQuarantineDispose)
	rework := authorization.RequirePermission(middleware.PermissionInboundRework)
	cancel := authorization.RequirePermission(middleware.PermissionInboundCancel)

	group.POST("/purchase-orders", plan, controller.CreatePurchaseOrder)
	group.GET("/purchase-orders", read, controller.ListPurchaseOrders)
	group.GET("/purchase-orders/:id", read, controller.GetPurchaseOrder)
	group.PUT("/purchase-orders/:id", plan, controller.UpdatePurchaseOrder)
	group.POST("/purchase-orders/:id/lines", plan, controller.AddPurchaseOrderLine)
	group.PUT("/purchase-orders/:id/lines/:line_id", plan, controller.UpdatePurchaseOrderLine)
	group.DELETE("/purchase-orders/:id/lines/:line_id", plan, controller.DeletePurchaseOrderLine)
	group.POST("/purchase-orders/:id/approve", approve, controller.ApprovePurchaseOrder)
	group.POST("/purchase-orders/:id/close", approve, controller.ClosePurchaseOrder)
	group.POST("/purchase-orders/:id/cancel", cancel, controller.CancelPurchaseOrder)
	group.POST("/orders", plan, controller.CreateInboundOrder)
	group.GET("/orders", read, controller.ListInboundOrders)
	group.GET("/orders/:id", read, controller.GetInboundOrder)
	group.PUT("/orders/:id", plan, controller.UpdateInboundOrder)
	group.POST("/orders/:id/lines", plan, controller.AddInboundOrderLine)
	group.PUT("/orders/:id/lines/:line_id", plan, controller.UpdateInboundOrderLine)
	group.DELETE("/orders/:id/lines/:line_id", plan, controller.DeleteInboundOrderLine)
	group.POST("/orders/:id/release", approve, controller.ReleaseInboundOrder)
	group.POST("/orders/:id/close", approve, controller.CloseInboundOrder)
	group.POST("/orders/:id/cancel", cancel, controller.CancelInboundOrder)
	group.POST("/receipts", receive, controller.CreateReceipt)
	group.GET("/receipts", read, controller.ListReceipts)
	group.GET("/receipts/:id", read, controller.GetReceipt)
	group.PUT("/receipts/:id", receive, controller.UpdateReceipt)
	group.POST("/receipts/:id/complete", receive, controller.CompleteReceipt)
	group.POST("/receipts/:id/cancel", cancel, controller.CancelReceipt)
	group.POST("/receipts/:id/reverse", cancel, controller.ReverseReceipt)
	group.POST("/quality-inspections", qc, controller.CreateQualityInspection)
	group.GET("/quality-inspections", read, controller.ListQualityInspections)
	group.GET("/quality-inspections/:id", read, controller.GetQualityInspection)
	group.POST("/quality-inspections/:id/complete", qc, controller.CompleteQualityInspection)
	group.POST("/quality-inspections/:id/cancel", cancel, controller.CancelQualityInspection)
	group.GET("/putaway-tasks", read, controller.ListPutawayTasks)
	group.GET("/putaway-tasks/:id", read, controller.GetPutawayTask)
	group.GET("/putaway-tasks/:id/assignees", assign, controller.ListPutawayAssignees)
	group.GET("/putaway-tasks/:id/targets", assign, controller.ListPutawayTargets)
	group.POST("/putaway-tasks/:id/start", putaway, controller.StartPutawayTask)
	group.POST("/putaway-tasks/:id/complete", putaway, controller.CompletePutawayTask)
	group.POST("/putaway-tasks/:id/assign", assign, controller.AssignPutawayTask)
	group.POST("/putaway-tasks/:id/retarget", assign, controller.RetargetPutawayTask)
	group.POST("/putaway-tasks/:id/cancel", cancel, controller.CancelPutawayTask)
	group.POST("/putaway-tasks/:id/reverse", cancel, controller.ReversePutawayTask)
	group.GET("/quarantine-disposition-types", read, controller.ListQuarantineDispositionTypes)
	group.GET("/quarantine-cases", read, controller.ListQuarantineCases)
	group.GET("/quarantine-cases/:id", read, controller.GetQuarantineCase)
	group.POST("/quarantine-cases/:id/dispositions", dispose, controller.CreateQuarantineDisposition)
	group.GET("/exceptions", read, controller.ListInboundExceptions)
	group.GET("/exceptions/:id", read, controller.GetInboundException)
	group.GET("/rework-tasks", read, controller.ListReworkTasks)
	group.GET("/rework-tasks/:id", read, controller.GetReworkTask)
	group.POST("/rework-tasks/:id/start", rework, controller.StartReworkTask)
	group.POST("/rework-tasks/:id/complete", rework, controller.CompleteReworkTask)
}
