package routes

import (
	"github.com/gin-gonic/gin"
	controller "wms-api/controller/master"
)

func registerOperationalRoutes(api *gin.RouterGroup, controller *controller.OperationalController, requireSession gin.HandlerFunc) {
	master := api.Group("/master")
	master.Use(requireSession)
	master.GET("/modules", controller.ListAppModule)
	master.GET("/modules/:id", controller.GetAppModule)
	master.POST("/modules", controller.CreateAppModule)
	master.PUT("/modules/:id", controller.UpdateAppModule)
	master.PATCH("/modules/:id/deactivate", controller.DeactivateAppModule)
	master.GET("/workflow-permissions", controller.ListAppPermission)
	master.GET("/workflow-permissions/:id", controller.GetAppPermission)
	master.GET("/document-types", controller.ListDocumentType)
	master.GET("/document-types/:id", controller.GetDocumentType)
	master.POST("/document-types", controller.CreateDocumentType)
	master.PUT("/document-types/:id", controller.UpdateDocumentType)
	master.PATCH("/document-types/:id/deactivate", controller.DeactivateDocumentType)
	master.GET("/document-types/:id/statuses", controller.ListDocumentStatus)
	master.GET("/document-types/:id/statuses/:child_id", controller.GetDocumentStatus)
	master.POST("/document-types/:id/statuses", controller.CreateDocumentStatus)
	master.PUT("/document-types/:id/statuses/:child_id", controller.UpdateDocumentStatus)
	master.PATCH("/document-types/:id/statuses/:child_id/deactivate", controller.DeactivateDocumentStatus)
	master.GET("/document-types/:id/transitions", controller.ListDocumentStatusTransition)
	master.GET("/document-types/:id/transitions/:child_id", controller.GetDocumentStatusTransition)
	master.POST("/document-types/:id/transitions", controller.CreateDocumentStatusTransition)
	master.PUT("/document-types/:id/transitions/:child_id", controller.UpdateDocumentStatusTransition)
	master.PATCH("/document-types/:id/transitions/:child_id/deactivate", controller.DeactivateDocumentStatusTransition)
	master.GET("/task-types", controller.ListTaskType)
	master.GET("/task-types/:id", controller.GetTaskType)
	master.POST("/task-types", controller.CreateTaskType)
	master.PUT("/task-types/:id", controller.UpdateTaskType)
	master.PATCH("/task-types/:id/deactivate", controller.DeactivateTaskType)
	master.GET("/task-statuses", controller.ListTaskStatus)
	master.GET("/task-statuses/:id", controller.GetTaskStatus)
	master.POST("/task-statuses", controller.CreateTaskStatus)
	master.PUT("/task-statuses/:id", controller.UpdateTaskStatus)
	master.PATCH("/task-statuses/:id/deactivate", controller.DeactivateTaskStatus)
	master.GET("/task-transitions", controller.ListTaskStatusTransition)
	master.GET("/task-transitions/:id", controller.GetTaskStatusTransition)
	master.POST("/task-transitions", controller.CreateTaskStatusTransition)
	master.PUT("/task-transitions/:id", controller.UpdateTaskStatusTransition)
	master.PATCH("/task-transitions/:id/deactivate", controller.DeactivateTaskStatusTransition)
	master.GET("/task-priorities", controller.ListTaskPriority)
	master.GET("/task-priorities/:id", controller.GetTaskPriority)
	master.POST("/task-priorities", controller.CreateTaskPriority)
	master.PUT("/task-priorities/:id", controller.UpdateTaskPriority)
	master.PATCH("/task-priorities/:id/deactivate", controller.DeactivateTaskPriority)
	master.GET("/picking-sort-methods", controller.ListPickingSortMethod)
	master.GET("/picking-sort-methods/:id", controller.GetPickingSortMethod)
	master.POST("/picking-sort-methods", controller.CreatePickingSortMethod)
	master.PUT("/picking-sort-methods/:id", controller.UpdatePickingSortMethod)
	master.PATCH("/picking-sort-methods/:id/deactivate", controller.DeactivatePickingSortMethod)
	master.GET("/picking-strategies", controller.ListPickingStrategy)
	master.GET("/picking-strategies/:id", controller.GetPickingStrategy)
	master.POST("/picking-strategies", controller.CreatePickingStrategy)
	master.PUT("/picking-strategies/:id", controller.UpdatePickingStrategy)
	master.PATCH("/picking-strategies/:id/deactivate", controller.DeactivatePickingStrategy)
	master.GET("/picking-strategies/:id/rules", controller.ListPickingStrategyRule)
	master.GET("/picking-strategies/:id/rules/:child_id", controller.GetPickingStrategyRule)
	master.POST("/picking-strategies/:id/rules", controller.CreatePickingStrategyRule)
	master.PUT("/picking-strategies/:id/rules/:child_id", controller.UpdatePickingStrategyRule)
	master.PATCH("/picking-strategies/:id/rules/:child_id/deactivate", controller.DeactivatePickingStrategyRule)
	master.GET("/putaway-strategies", controller.ListPutawayStrategy)
	master.GET("/putaway-strategies/:id", controller.GetPutawayStrategy)
	master.POST("/putaway-strategies", controller.CreatePutawayStrategy)
	master.PUT("/putaway-strategies/:id", controller.UpdatePutawayStrategy)
	master.PATCH("/putaway-strategies/:id/deactivate", controller.DeactivatePutawayStrategy)
	master.GET("/putaway-strategies/:id/rules", controller.ListPutawayStrategyRule)
	master.GET("/putaway-strategies/:id/rules/:child_id", controller.GetPutawayStrategyRule)
	master.POST("/putaway-strategies/:id/rules", controller.CreatePutawayStrategyRule)
	master.PUT("/putaway-strategies/:id/rules/:child_id", controller.UpdatePutawayStrategyRule)
	master.PATCH("/putaway-strategies/:id/rules/:child_id/deactivate", controller.DeactivatePutawayStrategyRule)

	master.GET("/document-types/:id/number-rules", controller.ListDocumentNumberRule)
	master.POST("/document-types/:id/number-rules", controller.ReplaceDocumentNumberRule)
	master.PATCH("/document-types/:id/number-rules/:child_id/deactivate", controller.DeactivateDocumentNumberRule)
	master.POST("/document-types/:id/document-ids", controller.GenerateDocumentID)
	master.GET("/document-types/:id/daily-counters", controller.ListDocumentDailyCounter)
}
