package routes

import (
	"github.com/gin-gonic/gin"
	controller "wms-api/controller/outbound"
)

func registerOutboundRoutes(api *gin.RouterGroup, controller *controller.Controller, requireSession gin.HandlerFunc) {
	group := api.Group("/outbound")
	group.Use(requireSession)
	group.Use(controller.RequireScope())
	group.POST("/orders", controller.CreateOrder)
	group.GET("/orders", controller.ListOrders)
	group.GET("/orders/:id", controller.GetOrder)
	group.PUT("/orders/:id", controller.UpdateOrder)
	group.POST("/orders/:id/lines", controller.AddOrderLine)
	group.PUT("/orders/:id/lines/:line_id", controller.UpdateOrderLine)
	group.DELETE("/orders/:id/lines/:line_id", controller.DeleteOrderLine)
	group.POST("/orders/:id/validate", controller.ValidateOrder)
	group.POST("/orders/:id/release", controller.ReleaseOrder)
	group.POST("/orders/:id/cancel", controller.CancelOrder)
	group.POST("/orders/:id/allocate", controller.AllocateOrder)
	group.GET("/validation-runs/:id", controller.GetValidationRun)
	group.GET("/reservations", controller.ListReservations)
	group.POST("/reservations/:id/release", controller.ReleaseReservation)
	group.POST("/waves", controller.CreateWave)
	group.GET("/waves", controller.ListWaves)
	group.GET("/waves/:id", controller.GetWave)
	group.POST("/waves/:id/release", controller.ReleaseWave)
	group.POST("/waves/:id/cancel", controller.CancelWave)
	group.GET("/pick-tasks", controller.ListPickTasks)
	group.GET("/pick-tasks/:id", controller.GetPickTask)
	group.POST("/pick-tasks/:id/start", controller.StartPickTask)
	group.POST("/pick-tasks/:id/confirm", controller.ConfirmPick)
	group.POST("/pick-tasks/:id/short-close", controller.CloseShortPick)
	group.POST("/stagings", controller.CreateStaging)
	group.GET("/stagings", controller.ListStagings)
	group.GET("/stagings/:id", controller.GetStaging)
	group.POST("/stagings/:id/complete", controller.CompleteStaging)
	group.POST("/checks", controller.CreateCheck)
	group.GET("/checks", controller.ListChecks)
	group.GET("/checks/:id", controller.GetCheck)
	group.POST("/checks/:id/lines/:line_id", controller.RecordCheckLine)
	group.POST("/checks/:id/complete", controller.CompleteCheck)
	group.GET("/checks/:id/exceptions", controller.ListCheckExceptions)
	group.POST("/check-exceptions/:id/resolve", controller.ResolveCheckException)
	group.POST("/check-exceptions/:id/replacements", controller.CreateReplacementPick)
	group.POST("/packings", controller.CreatePacking)
	group.GET("/packings", controller.ListPackings)
	group.GET("/packings/:id", controller.GetPacking)
	group.POST("/packings/:id/lines/:line_id", controller.PackLine)
	group.POST("/packings/:id/complete", controller.CompletePacking)
	group.POST("/packings/:id/cancel", controller.CancelPacking)
	group.POST("/carriers", controller.CreateCarrier)
	group.GET("/carriers", controller.ListCarriers)
	group.GET("/carriers/:id", controller.GetCarrier)
	group.PUT("/carriers/:id", controller.UpdateCarrier)
	group.POST("/carriers/:id/services", controller.CreateCarrierService)
	group.GET("/carriers/:id/services", controller.ListCarrierServices)
	group.GET("/carriers/:id/services/:service_id", controller.GetCarrierService)
	group.PUT("/carriers/:id/services/:service_id", controller.UpdateCarrierService)
	group.POST("/carriers/:id/drivers", controller.CreateCarrierDriver)
	group.GET("/carriers/:id/drivers", controller.ListCarrierDrivers)
	group.GET("/carriers/:id/drivers/:driver_id", controller.GetCarrierDriver)
	group.PUT("/carriers/:id/drivers/:driver_id", controller.UpdateCarrierDriver)
	group.POST("/shipments", controller.CreateShipment)
	group.GET("/shipments", controller.ListShipments)
	group.GET("/shipments/:id", controller.GetShipment)
	group.POST("/shipments/:id/lines/:line_id/dispatch", controller.DispatchShipmentLine)
	group.POST("/shipments/:id/complete", controller.CompleteShipment)
	group.POST("/shipments/:id/cancel", controller.CancelShipment)
	group.POST("/shipments/:id/drivers", controller.AssignShipmentDriver)
	group.GET("/shipments/:id/drivers", controller.ListShipmentDrivers)
	group.DELETE("/shipments/:id/drivers/:driver_id", controller.RemoveShipmentDriver)
	group.POST("/deliveries", controller.CreateDelivery)
	group.GET("/deliveries", controller.ListDeliveries)
	group.GET("/deliveries/:id", controller.GetDelivery)
	group.POST("/deliveries/:id/depart", controller.DepartDelivery)
	group.POST("/deliveries/:id/arrive", controller.ArriveDelivery)
	group.POST("/deliveries/:id/lines/:line_id/deliver", controller.DeliverLine)
	group.POST("/deliveries/:id/complete", controller.CompleteDelivery)
	group.POST("/deliveries/:id/fail", controller.FailDelivery)
	group.POST("/deliveries/:id/cancel", controller.CancelDelivery)
	group.POST("/deliveries/:id/lines/:line_id/return", controller.ReturnDeliveryLine)
	group.POST("/deliveries/:id/close-return", controller.CloseReturnedDelivery)
	group.PUT("/return-policy", controller.UpsertReturnPolicy)
	group.GET("/return-policy", controller.GetReturnPolicy)
}
