package routes

import (
	"github.com/gin-gonic/gin"
	controller "wms-api/controller/outbound"
	"wms-api/middleware"
)

func registerOutboundRoutes(api *gin.RouterGroup, controller *controller.Controller, authorization *middleware.Authentication) {
	group := api.Group("/outbound")
	group.Use(authorization.RequireSession())
	group.Use(controller.RequireScope())
	read := authorization.RequirePermission(middleware.PermissionOutboundRead)
	plan := authorization.RequirePermission(middleware.PermissionOutboundPlan)
	pick := authorization.RequirePermission(middleware.PermissionOutboundPick)
	stage := authorization.RequirePermission(middleware.PermissionOutboundStage)
	check := authorization.RequirePermission(middleware.PermissionOutboundCheck)
	pack := authorization.RequirePermission(middleware.PermissionOutboundPack)
	transport := authorization.RequirePermission(middleware.PermissionOutboundTransport)
	ship := authorization.RequirePermission(middleware.PermissionOutboundShip)
	deliver := authorization.RequirePermission(middleware.PermissionOutboundDeliver)
	cancel := authorization.RequirePermission(middleware.PermissionOutboundCancel)
	config := authorization.RequirePermission(middleware.PermissionOutboundConfig)

	group.POST("/orders", plan, controller.CreateOrder)
	group.GET("/orders", read, controller.ListOrders)
	group.GET("/orders/:id", read, controller.GetOrder)
	group.PUT("/orders/:id", plan, controller.UpdateOrder)
	group.POST("/orders/:id/lines", plan, controller.AddOrderLine)
	group.PUT("/orders/:id/lines/:line_id", plan, controller.UpdateOrderLine)
	group.DELETE("/orders/:id/lines/:line_id", plan, controller.DeleteOrderLine)
	group.POST("/orders/:id/validate", plan, controller.ValidateOrder)
	group.POST("/orders/:id/release", plan, controller.ReleaseOrder)
	group.POST("/orders/:id/cancel", cancel, controller.CancelOrder)
	group.POST("/orders/:id/allocate", plan, controller.AllocateOrder)
	group.GET("/validation-runs/:id", read, controller.GetValidationRun)
	group.GET("/reservations", read, controller.ListReservations)
	group.POST("/reservations/:id/release", plan, controller.ReleaseReservation)
	group.POST("/waves", plan, controller.CreateWave)
	group.GET("/waves", read, controller.ListWaves)
	group.GET("/waves/:id", read, controller.GetWave)
	group.POST("/waves/:id/release", plan, controller.ReleaseWave)
	group.POST("/waves/:id/cancel", cancel, controller.CancelWave)
	group.GET("/pick-tasks", read, controller.ListPickTasks)
	group.GET("/pick-tasks/:id", read, controller.GetPickTask)
	group.POST("/pick-tasks/:id/start", pick, controller.StartPickTask)
	group.POST("/pick-tasks/:id/confirm", pick, controller.ConfirmPick)
	group.POST("/pick-tasks/:id/short-close", pick, controller.CloseShortPick)
	group.POST("/stagings", stage, controller.CreateStaging)
	group.GET("/stagings", read, controller.ListStagings)
	group.GET("/stagings/:id", read, controller.GetStaging)
	group.POST("/stagings/:id/complete", stage, controller.CompleteStaging)
	group.POST("/checks", check, controller.CreateCheck)
	group.GET("/checks", read, controller.ListChecks)
	group.GET("/checks/:id", read, controller.GetCheck)
	group.POST("/checks/:id/lines/:line_id", check, controller.RecordCheckLine)
	group.POST("/checks/:id/complete", check, controller.CompleteCheck)
	group.GET("/checks/:id/exceptions", read, controller.ListCheckExceptions)
	group.POST("/check-exceptions/:id/resolve", check, controller.ResolveCheckException)
	group.POST("/check-exceptions/:id/replacements", check, controller.CreateReplacementPick)
	group.POST("/packings", pack, controller.CreatePacking)
	group.GET("/packings", read, controller.ListPackings)
	group.GET("/packings/:id", read, controller.GetPacking)
	group.POST("/packings/:id/lines/:line_id", pack, controller.PackLine)
	group.POST("/packings/:id/complete", pack, controller.CompletePacking)
	group.POST("/packings/:id/cancel", cancel, controller.CancelPacking)
	group.POST("/carriers", transport, controller.CreateCarrier)
	group.GET("/carriers", read, controller.ListCarriers)
	group.GET("/carriers/:id", read, controller.GetCarrier)
	group.PUT("/carriers/:id", transport, controller.UpdateCarrier)
	group.POST("/carriers/:id/services", transport, controller.CreateCarrierService)
	group.GET("/carriers/:id/services", read, controller.ListCarrierServices)
	group.GET("/carriers/:id/services/:service_id", read, controller.GetCarrierService)
	group.PUT("/carriers/:id/services/:service_id", transport, controller.UpdateCarrierService)
	group.POST("/carriers/:id/drivers", transport, controller.CreateCarrierDriver)
	group.GET("/carriers/:id/drivers", read, controller.ListCarrierDrivers)
	group.GET("/carriers/:id/drivers/:driver_id", read, controller.GetCarrierDriver)
	group.PUT("/carriers/:id/drivers/:driver_id", transport, controller.UpdateCarrierDriver)
	group.POST("/shipments", ship, controller.CreateShipment)
	group.GET("/shipments", read, controller.ListShipments)
	group.GET("/shipments/:id", read, controller.GetShipment)
	group.POST("/shipments/:id/lines/:line_id/dispatch", ship, controller.DispatchShipmentLine)
	group.POST("/shipments/:id/complete", ship, controller.CompleteShipment)
	group.POST("/shipments/:id/cancel", cancel, controller.CancelShipment)
	group.POST("/shipments/:id/drivers", ship, controller.AssignShipmentDriver)
	group.GET("/shipments/:id/drivers", read, controller.ListShipmentDrivers)
	group.DELETE("/shipments/:id/drivers/:driver_id", ship, controller.RemoveShipmentDriver)
	group.POST("/deliveries", deliver, controller.CreateDelivery)
	group.GET("/deliveries", read, controller.ListDeliveries)
	group.GET("/deliveries/:id", read, controller.GetDelivery)
	group.POST("/deliveries/:id/depart", deliver, controller.DepartDelivery)
	group.POST("/deliveries/:id/arrive", deliver, controller.ArriveDelivery)
	group.POST("/deliveries/:id/lines/:line_id/deliver", deliver, controller.DeliverLine)
	group.POST("/deliveries/:id/complete", deliver, controller.CompleteDelivery)
	group.POST("/deliveries/:id/fail", deliver, controller.FailDelivery)
	group.POST("/deliveries/:id/cancel", cancel, controller.CancelDelivery)
	group.POST("/deliveries/:id/lines/:line_id/return", deliver, controller.ReturnDeliveryLine)
	group.POST("/deliveries/:id/close-return", deliver, controller.CloseReturnedDelivery)
	group.PUT("/return-policy", config, controller.UpsertReturnPolicy)
	group.GET("/return-policy", read, controller.GetReturnPolicy)
}
