import type { DispositionType, QuarantineCase } from "./quarantine-types";
export const testCase: QuarantineCase = {
  quarantine_case_id: "QCASE-1",
  inspection_id: "QC-1",
  receipt_inventory_id: "BATCH-1",
  quarantine_balance_id: "balance-1",
  quarantine_balance_version_no: 7,
  available_qty: "10.000000",
  base_uom_code: "EA",
  is_indivisible: false,
  owner_id: "owner-1",
  warehouse_id: "warehouse-1",
  item_id: "item-1",
  item_code: "ITEM-1",
  lot_number: "LOT-1",
  location_code: "QC-AREA",
  status_code: "OPEN",
  quarantine_qty: "10.000000",
  disposed_qty: "0.000000",
  uom_id: "uom-1",
  opened_at: "2026-09-17T09:00:00+07:00",
  version_no: 2,
  dispositions: [],
};
export const testTypes: DispositionType[] = [
  {
    quarantine_disposition_type_id: "type-1",
    code: "ACCEPT",
    name: "Accept",
    is_active: true,
    releases_to_available: true,
    requires_reinspection: false,
    removes_inventory: false,
  },
  {
    quarantine_disposition_type_id: "type-2",
    code: "RETURN",
    name: "Return",
    is_active: true,
    releases_to_available: false,
    requires_reinspection: false,
    removes_inventory: true,
  },
  {
    quarantine_disposition_type_id: "type-3",
    code: "DISPOSE",
    name: "Dispose",
    is_active: true,
    releases_to_available: false,
    requires_reinspection: false,
    removes_inventory: true,
  },
  {
    quarantine_disposition_type_id: "type-4",
    code: "REWORK",
    name: "Rework",
    is_active: true,
    releases_to_available: false,
    requires_reinspection: true,
    removes_inventory: false,
  },
];
